"""add permission settings to trips

Revision ID: aaf26d6d6209
Revises: ee5f4257ad7c
Create Date: 2026-02-13 22:05:11.894738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaf26d6d6209'
down_revision: Union[str, Sequence[str], None] = 'ee5f4257ad7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('allow_member_edit_expenses', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('trips', sa.Column('allow_member_self_join', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'allow_member_self_join')
    op.drop_column('trips', 'allow_member_edit_expenses')
    # ### end Alembic commands ###
